version: "3.9"
services:
  postgres:
    container_name: postgres-1
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@baeldung.com
      PGADMIN_DEFAULT_PASSWORD: baeldung
    ports:
      - "5050:80"

volumes:
  postgres:
    driver: local

